apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2020-09-19T17:05:50Z'
  generation: 1
  labels:
    app: activiti-modeling-app
  name: activiti-modeling-app
  namespace: jointdev-aurora-app
  resourceVersion: '443659627'
  selfLink: >-
    /apis/apps/v1/namespaces/jointdev-aurora-app/deployments/activiti-modeling-app
  uid: 1b6cbabc-5c2a-4325-96a7-feb33ed484b7
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: activiti-modeling-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: activiti-modeling-app
    spec:
      containers:
        - image: >-
            registry-intl-vpc.ap-southeast-3.aliyuncs.com/jointdev-aurora-coresi/activiti-modeling-app:latest
          imagePullPolicy: Always
          name: activiti-modeling-app
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 2Gi
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
    - lastTransitionTime: '2020-09-19T17:05:52Z'
      lastUpdateTime: '2020-09-19T17:05:52Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-09-19T17:05:50Z'
      lastUpdateTime: '2020-09-19T17:05:52Z'
      message: >-
        ReplicaSet "activiti-modeling-app-5bd7cff466" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
