apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2020-09-19T17:06:23Z'
  generation: 1
  labels:
    app: activiti-nginx
  name: activiti-nginx
  namespace: jointdev-aurora-app
  resourceVersion: '443675118'
  selfLink: /apis/apps/v1/namespaces/jointdev-aurora-app/deployments/activiti-nginx
  uid: 523fec92-02c1-48c8-9921-a731a4911de5
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: activiti-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: activiti-nginx
    spec:
      containers:
        - image: >-
            registry-intl-vpc.ap-southeast-3.aliyuncs.com/jointdev-aurora-coresi/activiti-nginx:latest
          imagePullPolicy: Always
          name: activiti-nginx
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 2Gi
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-09-19T17:06:23Z'
      lastUpdateTime: '2020-09-19T17:06:23Z'
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: 'False'
      type: Available
    - lastTransitionTime: '2020-09-19T17:16:25Z'
      lastUpdateTime: '2020-09-19T17:16:25Z'
      message: ReplicaSet "activiti-nginx-86865485c7" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: 'False'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 2
