apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2020-09-19T17:04:13Z'
  generation: 1
  labels:
    app: activiti
    component: keycloak
    env: staging
  name: activiti-keycloak
  namespace: jointdev-aurora-app
  resourceVersion: '443657225'
  selfLink: /apis/apps/v1/namespaces/jointdev-aurora-app/deployments/activiti-keycloak
  uid: 9a6b74bf-9af3-4bfa-9255-aadcb10ad74f
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: activiti-keycloak
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: activiti-keycloak
    spec:
      containers:
        - image: >-
            registry-intl-vpc.ap-southeast-3.aliyuncs.com/jointdev-aurora-coresi/activiti-keycloak:latest
          imagePullPolicy: Always
          name: activiti-keycloak
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 2Gi
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
    - lastTransitionTime: '2020-09-19T17:04:16Z'
      lastUpdateTime: '2020-09-19T17:04:16Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-09-19T17:04:14Z'
      lastUpdateTime: '2020-09-19T17:04:16Z'
      message: ReplicaSet "activiti-keycloak-66b6c4d886" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
