apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2020-09-19T17:05:19Z'
  generation: 1
  labels:
    app: activiti-cloud-modeling
  name: activiti-cloud-modeling
  namespace: jointdev-aurora-app
  resourceVersion: '443658858'
  selfLink: >-
    /apis/apps/v1/namespaces/jointdev-aurora-app/deployments/activiti-cloud-modeling
  uid: 50973e25-309b-4438-beee-6dbfef9ea53f
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: activiti-cloud-modeling
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: activiti-cloud-modeling
    spec:
      containers:
        - image: >-
            registry-intl-vpc.ap-southeast-3.aliyuncs.com/jointdev-aurora-coresi/activiti-cloud-modeling:latest
          imagePullPolicy: Always
          name: activiti-cloud-modeling
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 2Gi
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
    - lastTransitionTime: '2020-09-19T17:05:22Z'
      lastUpdateTime: '2020-09-19T17:05:22Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-09-19T17:05:19Z'
      lastUpdateTime: '2020-09-19T17:05:22Z'
      message: >-
        ReplicaSet "activiti-cloud-modeling-5979b55b8" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
